# Generated by Django 2.2.4 on 2019-08-14 19:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context_text', '0027_auto_20190508_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proquest_HNP_Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_identifier', models.CharField(max_length=255, unique=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('compressed_folder_path', models.TextField(blank=True, null=True)),
                ('uncompressed_folder_path', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('newspaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_text.Newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='Proquest_HNP_Object_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('related_model', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('raw_value', models.TextField(unique=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_text_proquest_hnp.Proquest_HNP_Object_Type')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Proquest_HNP_Newspaper_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_identifier', models.CharField(max_length=255, unique=True)),
                ('compressed_file_path', models.TextField(blank=True, null=True)),
                ('uncompressed_folder_path', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('proquest_hnp_newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_text_proquest_hnp.Proquest_HNP_Newspaper')),
            ],
        ),
        migrations.CreateModel(
            name='PHNP_Newspaper_Object_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('proquest_hnp_newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_text_proquest_hnp.Proquest_HNP_Newspaper')),
                ('proquest_hnp_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_text_proquest_hnp.Proquest_HNP_Object_Type')),
            ],
        ),
        migrations.CreateModel(
            name='PHNP_Newspaper_Archive_Object_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('proquest_hnp_newspaper_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_text_proquest_hnp.Proquest_HNP_Newspaper_Archive')),
                ('proquest_hnp_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_text_proquest_hnp.Proquest_HNP_Object_Type')),
            ],
        ),
    ]
