# Generated by Django 2.2.4 on 2019-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text_proquest_hnp', '0002_proquest_hnp_newspaper_archive_file_name_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='proquest_hnp_object_type',
            name='raw_value_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proquest_hnp_object_type',
            name='raw_value_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proquest_hnp_object_type',
            name='raw_value_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proquest_hnp_object_type',
            name='raw_value_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
