# Generated by Django 2.2.4 on 2019-08-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_text_proquest_hnp', '0005_auto_20190817_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proquest_hnp_object_type',
            options={'ordering': ['raw_value']},
        ),
    ]
